const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  LOAD_SCAN_RESULTS: "LOAD_SCAN_RESULTS",
    LOAD_AGENTS: "LOAD_AGENTS",
    SET_ALERT : "SET_ALERT",
    REMOVE_ALERT : "REMOVE_ALERT"
};

export default ACTIONS;